### ISSUE TITLE
Potential Conflict with 5CE Exception

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#57] opened 2019-10-24 18:12 UTC
![2019-10-24_0310_(5CE_question)](https://user-images.githubusercontent.com/48993588/67513074-f502e380-f64e-11e9-8fe1-a211328c0879.png)

Due to the exception, Valetta needs to reason whether or not this is a Reverse Finesse and thus a play clue on the i5. 

Because Dr_Kakashi avoided picking up B5, she can reason it is not a play clue on i5 but a 5CE.

**Comment by sjdrodge** [comment] 2019-10-24 21:58
As discussed extensively in other channels, this example does not indicate any problem with the existing conventions.

**Comment by Dr-Kakashi** [comment] 2019-10-24 22:05
There is.  The main reason why it mentions an exception is because ejections are defined as the immediate next player.  Obviously, it won't be the immediate next player if they deferred because they think they're reversed finessed.  This is a situation where they could be reversed finessed; however, they know they aren't because 5's would've been given as a play clue.

**Comment by aliblong** [comment] 2019-10-24 22:15
Why not just use the other 5? That is a general solution to this very narrow problem.

**Comment by Dr-Kakashi** [comment] 2019-10-24 22:18
Choosing i5 directly identifies it at the cost of efficiency.  Now the team has to spend a clue to save N5 and B5 when they get to chop.  

If N5 was chosen for the ejection, it would be higher efficiency.  However, when blue 5 gets to chop and is 5 saved, the i5 can be either i345.  Assuming that i2 will be gotten before then.

**Comment by efaust** [comment] 2019-10-24 22:21
I don't see why we need to codify every context read. Yes, the clue as given is TECHNICALLY a reverse finesse, so invalid. However, the existence of 5s makes it likely that this will be correctly read as an ejection. What's the problem?

**Comment by sjdrodge** [comment] 2019-10-24 22:23
@Dr-Kakashi I will repeat the explanation here for the record. Every convention will have contextual exceptions to it on the basis that a "clearly better" move was available in some particular board state. Since this type of exception applies to every single convention that we have, finding an example does not indicate a problem with the convention. If you have some proposed change to the convention based off of this situation (where the general agreement is that you should simply choose one of the other available 5ce that doesn't require a context read), then feel free to propose it, but the only thing I could imagine adding from this is "unless the clue is otherwise clearly suboptimal" which is an addendum that could be added to every single convention we have.

**Comment by Dr-Kakashi** [comment] 2019-10-24 22:43
I honestly don't think you guys get it.......it isn't about codifying all the context reads nor about having and/or expecting players to understand the context reads.  It's about game theory because it's about getting better at the game.  Sure you guys are right in the sense that it'll clutter the document if we were to list all the contextual, edge cases, etc.  However, some players literally treat the doc as a bible.  Meaning they take it for what it is and not think outside of the box.  Maybe there shouldn't be changes to the doc, but there should be some sort of section for players to realize cases where the doc may not be 100% correct.

**Comment by sjdrodge** [comment] 2019-10-24 22:53
> honestly don't think you guys get it.......it isn't about codifying all the context reads nor about having and/or expecting players to understand the context reads.

Seeing as you proposed codifying what should just be a context read, I believe our criticism on that front is warranted.

> It's about game theory because it's about getting better at the game.

I don't know what to make of this sentence.

> Sure you guys are right in the sense that it'll clutter the document if we were to list all the contextual, edge cases, etc. However, some players literally treat the doc as a bible. Meaning they take it for what it is and not think outside of the box. Maybe there shouldn't be changes to the doc, but there should be some sort of section for players to realize cases where the doc may not be 100% correct because there are "exceptions."

This sounds like a sensible proposal. Having a section of the document instructing everybody to take it with a grain of salt and understand that context is part of the game may help reduce the frequency of players treating it "as a bible." I encourage you to write a rough draft of such a section and post it as a separate proposal.

As for this proposal, I think it's time to close it. @Zamiell

**Comment by aliblong** [comment] 2019-10-24 23:03
Almost every item in the doc can be viewed as an exception to a previously stated rule. If the issue is how to communicate to players that we don't use the doc as an algorithm... sure, we can write something explicit to that effect, but to me, it seems like a waste of time to explicitly acknowledge the infinite complexity of something relating to a living system.

**Comment by Dr-Kakashi** [comment] 2019-10-25 08:09
There are times in the doc where things are worded in a way that causes confusion.  A good example is the Free Choice Finesse where it used to say the clue touches a "sole" card.  The intention was to let players know that the "focus" was the rainbow card.  It may also be the case where intuitively if a choice of colors can be done then the free choice finesse should apply.  Picking up 2 rainbow cards for example.  However, players can take it for what it said in the doc, where only 1 or sole card is touched and a free choice of colors can be done.

**Comment by Zamiell** [comment] 2019-10-27 09:37
if you think the doc section on 5CE can be more clear can you just submit a pull request?

**Comment by Zamiell** [comment] 2019-10-29 19:30
> However, some players literally treat the doc as a bible

i dont think anyone treats the doc as a bible

**Comment by Zamiell** [comment] 2019-11-08 18:08
/stale closing this since kakashi isn't responding

**Closed by Zamiell** 2019-11-08 18:08 UTC
Labels: clarification
